name: Deploy Frontend (InfinityFree)

on:
  push:
    branches: ["main"]
    paths:
      - "Frontend/**" # Chỉ chạy khi sửa file trong thư mục Frontend
      - ".github/workflows/fe.yml"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Vì là HTML tĩnh nên không cần bước Build nào cả

      - name: Upload to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.IF_HOST }}
          username: ${{ secrets.IF_USER }}
          password: ${{ secrets.IF_PASS }}

          # Chỉ upload nội dung TRONG thư mục Frontend
          local-dir: ./Frontend/

          # Upload vào thư mục htdocs của InfinityFree
          server-dir: /htdocs/

          # Quan trọng: Tránh xóa nhầm file hệ thống của họ
          exclude: |
            **/.git*
            **/.git*/**
            .htaccess
            override
